version: 2
updates:
  - package-ecosystem: npm
    directory: /Website
    schedule:
      interval: weekly
    groups:
      website:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
