// Generated by Scripts/generate_showcase_manifest.py from Registry metadata.
// Do not edit by hand; edit the item document and regenerate.

/// One registry item as the Showcase browses it.
struct CatalogEntry: Identifiable, Hashable, Sendable {
    let name: String
    let kind: String
    let version: String
    let description: String
    let usage: String
    let dependencies: [String]
    let tags: [String]

    var id: String { name }
}

enum RegistryCatalogManifest {
    static let entries: [CatalogEntry] = [
        CatalogEntry(
            name: "accordion",
            kind: "component",
            version: "0.2.0",
            description: "Styles a native DisclosureGroup as a full-width row header with a trailing chevron and content revealed beneath, keeping the caller's content styling, for stacked expandable sections.",
            usage: "@State private var isExpanded = false\n\nDisclosureGroup(\"How do I freeze my card?\", isExpanded: $isExpanded) {\n    Text(\"Open the card, then choose Freeze.\")\n}\n.disclosureGroupStyle(.registryAccordion)",
            dependencies: ["separator"],
            tags: ["accordion", "disclosure", "collapsible", "expand", "faq", "shadcn"]
        ),
        CatalogEntry(
            name: "activity-feed",
            kind: "block",
            version: "0.2.0",
            description: "Composes inline alert, avatar, item row, skeleton, empty state, and accordion treatments into an activity feed with caller-owned loading, items, notice, and selection.",
            usage: "ActivityFeed(\n    \"Activity\",\n    notice: ActivityNotice(\"Card delivery delayed\", message: Text(\"Arrives Thursday.\")),\n    onDismissNotice: { },\n    items: [\n        ActivityItem(\n            id: \"bakery\",\n            title: Text(\"Mishmash Bakery\"),\n            detail: Text(\"Card payment of KWD 8.750\"),\n            timestamp: Text(\"09:41\"),\n            initials: \"MB\",\n            senderName: Text(\"Mishmash Bakery\"),\n            isUnread: true\n        )\n    ],\n    earlierItems: [],\n    isLoading: false,\n    onSelect: { id in }\n)",
            dependencies: ["alert", "avatar", "item", "skeleton", "empty", "accordion", "separator", "button"],
            tags: ["activity", "feed", "inbox", "notifications", "timeline", "loading"]
        ),
        CatalogEntry(
            name: "alert",
            kind: "component",
            version: "0.1.1",
            description: "Composes an inline, non-modal status message with informational, positive, and destructive variants and optional caller-owned actions.",
            usage: "InlineAlert(\n    \"Card delivery delayed\",\n    message: Text(\"Your new card now arrives on Thursday.\")\n)\n\nInlineAlert(\n    \"Payment failed\",\n    message: Text(\"The card on file was declined.\"),\n    variant: .destructive\n) {\n    Button(\"Retry\") {}\n        .buttonStyle(.registry)\n}",
            dependencies: ["button"],
            tags: ["alert", "banner", "notice", "feedback", "status", "shadcn"]
        ),
        CatalogEntry(
            name: "alert-dialog",
            kind: "recipe",
            version: "0.1.0",
            description: "Native guidance for a modal decision with .alert, using button roles and prepared copy while keeping the system presentation.",
            usage: "@State private var isConfirmingSignOut = false\n\nButton(\"Sign out\", role: .destructive) {\n    isConfirmingSignOut = true\n}\n.alert(\"Sign out?\", isPresented: $isConfirmingSignOut) {\n    Button(\"Sign out\", role: .destructive) { }\n    Button(\"Cancel\", role: .cancel) { }\n} message: {\n    Text(\"You will need your password to sign in again.\")\n}",
            dependencies: [],
            tags: ["alert", "dialog", "confirm", "destructive", "modal", "guidance"]
        ),
        CatalogEntry(
            name: "aspect-ratio",
            kind: "recipe",
            version: "0.3.0",
            description: "Native guidance for SwiftUI's aspectRatio modifier without introducing a replacement API.",
            usage: "Color.indigo\n    .overlay {\n        Image(systemName: \"play.fill\")\n            .foregroundStyle(.white)\n            .accessibilityHidden(true)\n    }\n    .aspectRatio(16.0 / 9.0, contentMode: .fit)\n    .accessibilityLabel(\"Video placeholder\")\n\nColor.teal\n    .aspectRatio(1, contentMode: .fit)\n    .frame(maxWidth: 160)\n    .accessibilityLabel(\"Avatar placeholder\")",
            dependencies: [],
            tags: ["aspect-ratio", "layout", "media", "native", "guidance"]
        ),
        CatalogEntry(
            name: "auth-form",
            kind: "block",
            version: "0.3.1",
            description: "Composes registry input, button, and card treatments into a sign-in form with caller-owned credentials, validation messages, and submission state.",
            usage: "AuthForm(\n    \"Welcome back\",\n    identity: $email,\n    identityError: emailError,\n    password: $password,\n    passwordError: passwordError,\n    formError: formError,\n    isSubmitting: isSubmitting,\n    secondaryActionTitle: \"Forgot password?\",\n    onSecondaryAction: { },\n    onSubmit: { }\n)",
            dependencies: ["input", "button", "card"],
            tags: ["authentication", "sign-in", "form", "validation", "autofill"]
        ),
        CatalogEntry(
            name: "avatar",
            kind: "component",
            version: "0.2.0",
            description: "Displays a circular identity image with initials or symbol fallback, sized by the environment control size, with a required accessibility label.",
            usage: "Avatar(Image(\"maya\"), accessibilityLabel: Text(\"Maya Khalid\"))\n\nAvatar(initials: \"MK\", accessibilityLabel: Text(\"Maya Khalid\"))\n    .controlSize(.large)\n\nAvatar(accessibilityLabel: Text(\"Unknown sender\"))",
            dependencies: [],
            tags: ["avatar", "profile", "identity", "image", "initials", "shadcn"]
        ),
        CatalogEntry(
            name: "badge",
            kind: "component",
            version: "0.3.1",
            description: "Applies primary, secondary, outline, positive, and destructive badge treatments to native Text and Label content.",
            usage: "Text(\"New\")\n    .registryBadge()\n\nLabel(\"Completed\", systemImage: \"checkmark.circle.fill\")\n    .registryBadge(.positive)",
            dependencies: [],
            tags: ["badge", "label", "status", "category", "modifier"]
        ),
        CatalogEntry(
            name: "button",
            kind: "component",
            version: "0.5.0",
            description: "Styles native SwiftUI buttons with shadcn-inspired semantic variants while preserving roles and environment sizing.",
            usage: "// Content layer only. In toolbars, tab bars, or floating chrome the system supplies Liquid Glass; use .buttonStyle(.glass) or .buttonStyle(.glassProminent) there instead of .registry styles.\n\nButton(\"Save changes\") {}\n    .buttonStyle(.registry)\n\nButton(\"Cancel\") {}\n    .buttonStyle(.registryOutline)\n\nButton(\"Delete\", role: .destructive) {}\n    .buttonStyle(.registry)",
            dependencies: [],
            tags: ["button", "control", "action", "style", "shadcn"]
        ),
        CatalogEntry(
            name: "button-group",
            kind: "component",
            version: "0.2.1",
            description: "Styles every native button in a ControlGroup with one registry button variant while retaining the system group container.",
            usage: "// Content layer only. In toolbars, tab bars, or floating chrome the system supplies Liquid Glass; use .buttonStyle(.glass) or .buttonStyle(.glassProminent) there instead of .registry styles.\n\nControlGroup {\n    Button(\"Undo\", systemImage: \"arrow.uturn.backward\") {}\n    Button(\"Redo\", systemImage: \"arrow.uturn.forward\") {}\n}\n.controlGroupStyle(.registryButtons)",
            dependencies: ["button"],
            tags: ["button", "control-group", "action", "style"]
        ),
        CatalogEntry(
            name: "calendar",
            kind: "recipe",
            version: "0.1.0",
            description: "Native guidance for date selection with DatePicker in graphical style and MultiDatePicker for several dates.",
            usage: "@State private var date = Date.now\n@State private var dates: Set<DateComponents> = []\n\nDatePicker(\"Statement date\", selection: $date, displayedComponents: .date)\n    .datePickerStyle(.graphical)\n\nMultiDatePicker(\"Reminder days\", selection: $dates)",
            dependencies: [],
            tags: ["calendar", "date", "picker", "date-picker", "guidance"]
        ),
        CatalogEntry(
            name: "card",
            kind: "component",
            version: "0.2.0",
            description: "Styles a native GroupBox as a semantic bordered surface with adaptive label and content spacing.",
            usage: "GroupBox {\n    Text(\"Manage billing and renewal details from your account settings.\")\n} label: {\n    Label(\"Subscription\", systemImage: \"creditcard.fill\")\n}\n.groupBoxStyle(.registryCard)",
            dependencies: [],
            tags: ["card", "group-box", "surface", "container", "style"]
        ),
        CatalogEntry(
            name: "checkbox",
            kind: "component",
            version: "0.3.0",
            description: "Styles a native Toggle as a checkbox while preserving its binding, label, enabled state, and accessibility representation.",
            usage: "@State private var accepted = false\n\nToggle(\"Accept terms\", isOn: $accepted)\n    .toggleStyle(.registryCheckbox)",
            dependencies: [],
            tags: ["checkbox", "toggle", "selection", "form", "style"]
        ),
        CatalogEntry(
            name: "collapsible",
            kind: "recipe",
            version: "0.1.0",
            description: "Native guidance for a single expandable region with the default DisclosureGroup, distinct from the styled accordion.",
            usage: "@State private var isShowingDetails = false\n\nDisclosureGroup(\"Fee breakdown\", isExpanded: $isShowingDetails) {\n    LabeledContent(\"Transfer fee\", value: \"KWD 1.000\")\n    LabeledContent(\"Exchange margin\", value: \"KWD 0.450\")\n}",
            dependencies: [],
            tags: ["collapsible", "disclosure", "expand", "toggle", "guidance"]
        ),
        CatalogEntry(
            name: "command",
            kind: "component",
            version: "0.2.0",
            description: "Composes the registry input group, item rows, keycaps, and empty state into a search field over caller-filtered command sections.",
            usage: "@State private var query = \"\"\n\nCommandPalette(\n    query: $query,\n    prompt: \"Search actions\",\n    sections: [\n        CommandSection(id: \"actions\", title: \"Actions\", entries: [\n            CommandEntry(id: \"transfer\", title: Text(\"New transfer\"), systemImage: \"arrow.up.right\", shortcut: \"⌘T\", shortcutLabel: Text(\"Command T\"))\n        ])\n    ],\n    onSelect: { id in }\n)",
            dependencies: ["input-group", "item", "kbd", "empty", "separator", "button"],
            tags: ["command", "palette", "search", "spotlight", "shadcn"]
        ),
        CatalogEntry(
            name: "command-search",
            kind: "block",
            version: "0.2.0",
            description: "Composes the command palette and keycap treatments into a search screen with caller-owned query, filtering, sections, and a keyboard shortcut legend.",
            usage: "@State private var query = \"\"\n\nCommandSearch(\n    \"Search\",\n    query: $query,\n    prompt: \"Search actions and activity\",\n    sections: sections,\n    emptyDescription: Text(\"Try a payee, a card, or an action.\"),\n    shortcuts: [\n        CommandShortcutHint(\"Open search\", keys: \"⌘K\", keysLabel: Text(\"Command K\"))\n    ],\n    onSelect: { id in }\n)",
            dependencies: ["command", "kbd"],
            tags: ["search", "command", "palette", "shortcuts", "screen"]
        ),
        CatalogEntry(
            name: "context-menu",
            kind: "recipe",
            version: "0.1.0",
            description: "Native guidance for long-press actions with .contextMenu using labeled, role-tagged buttons.",
            usage: "TransactionRow(\n    title: Text(\"Mishmash Bakery\"),\n    subtitle: Text(\"Today, 09:41\"),\n    amount: Text(-8.75, format: .currency(code: \"KWD\")),\n    systemImage: \"cup.and.saucer.fill\",\n    tone: .negative\n)\n.contextMenu {\n    Button(\"Add note\", systemImage: \"square.and.pencil\") { }\n    Button(\"Share\", systemImage: \"square.and.arrow.up\") { }\n    Divider()\n    Button(\"Report\", systemImage: \"flag\", role: .destructive) { }\n}",
            dependencies: [],
            tags: ["context-menu", "long-press", "actions", "menu", "guidance"]
        ),
        CatalogEntry(
            name: "dialog",
            kind: "recipe",
            version: "0.1.0",
            description: "Native guidance for modal content with .sheet, leaving detents, drag dismissal, and focus to the system.",
            usage: "@State private var isEditing = false\n\nButton(\"Edit profile\") { isEditing = true }\n    .sheet(isPresented: $isEditing) {\n        NavigationStack {\n            ProfileEditor()\n                .navigationTitle(\"Edit profile\")\n                .toolbar {\n                    ToolbarItem(placement: .confirmationAction) {\n                        Button(\"Done\") { isEditing = false }\n                    }\n                }\n        }\n    }",
            dependencies: [],
            tags: ["dialog", "sheet", "modal", "presentation", "guidance"]
        ),
        CatalogEntry(
            name: "direction",
            kind: "recipe",
            version: "0.3.0",
            description: "Native guidance for layoutDirection behavior and semantic leading/trailing layout without a replacement API.",
            usage: "@Environment(\\.layoutDirection) private var layoutDirection\n\nHStack {\n    Image(systemName: \"person.crop.circle\")\n        .accessibilityHidden(true)\n    Text(\"Account\")\n    Spacer()\n    Image(systemName: \"chevron.forward\")\n        .accessibilityHidden(true)\n}",
            dependencies: [],
            tags: ["direction", "layout-direction", "rtl", "localization", "guidance"]
        ),
        CatalogEntry(
            name: "drawer",
            kind: "recipe",
            version: "0.1.0",
            description: "Native guidance for a bottom drawer using .sheet with presentation detents and a visible drag indicator.",
            usage: "@State private var isShowingFilters = false\n\nButton(\"Filters\") { isShowingFilters = true }\n    .sheet(isPresented: $isShowingFilters) {\n        FilterOptions()\n            .presentationDetents([.medium, .large])\n            .presentationDragIndicator(.visible)\n    }",
            dependencies: [],
            tags: ["drawer", "bottom-sheet", "detents", "sheet", "guidance"]
        ),
        CatalogEntry(
            name: "dropdown-menu",
            kind: "recipe",
            version: "0.1.0",
            description: "Native guidance for a Menu trigger with labeled actions, sections, and a picker inside the menu.",
            usage: "@State private var sort = \"recent\"\n\nMenu(\"Sort\", systemImage: \"arrow.up.arrow.down\") {\n    Picker(\"Sort by\", selection: $sort) {\n        Text(\"Most recent\").tag(\"recent\")\n        Text(\"Amount\").tag(\"amount\")\n    }\n    Divider()\n    Button(\"Export\", systemImage: \"square.and.arrow.up\") { }\n}\n.buttonStyle(.registryOutline)",
            dependencies: [],
            tags: ["dropdown", "menu", "actions", "picker", "guidance"]
        ),
        CatalogEntry(
            name: "empty",
            kind: "component",
            version: "0.1.0",
            description: "Places a native ContentUnavailableView on the registry content surface so an empty section sits where its rows would.",
            usage: "ContentUnavailableView(\n    \"No recent activity\",\n    systemImage: \"clock.arrow.circlepath\",\n    description: Text(\"New transactions will appear here.\")\n)\n.registryEmptyState()",
            dependencies: [],
            tags: ["empty", "placeholder", "content-unavailable", "state", "shadcn"]
        ),
        CatalogEntry(
            name: "field",
            kind: "component",
            version: "0.1.0",
            description: "Composes a labeled form field around a native control with an optional description and an error message that drives the content's invalid state.",
            usage: "@State private var email = \"\"\n\nFieldGroup {\n    Field(\"Full name\", description: \"As it appears on your card.\") { _ in\n        TextField(\"Full name\", text: $name)\n            .textFieldStyle(.registryInput)\n            .accessibilityLabel(\"Full name\")\n    }\n    Field(\"Email\", error: emailError) { isInvalid in\n        TextField(\"you@example.com\", text: $email)\n            .textFieldStyle(RegistryInputStyle(isInvalid: isInvalid))\n            .accessibilityLabel(\"Email\")\n    }\n}",
            dependencies: ["input"],
            tags: ["field", "form", "label", "validation", "error", "shadcn"]
        ),
        CatalogEntry(
            name: "finance-overview",
            kind: "block",
            version: "0.4.1",
            description: "Composes metrics and selectable transactions into an embeddable finance overview without owning navigation or state.",
            usage: "FinanceOverview(\n    \"Overview\",\n    balanceTitle: \"Available balance\",\n    balance: Text(12_480.32, format: .currency(code: \"USD\")),\n    changeTitle: \"Monthly change\",\n    change: Text(0.082, format: .percent),\n    sectionTitle: \"Recent activity\",\n    transactions: [\n        FinanceTransactionItem(\n            id: \"salary\",\n            title: Text(\"Salary\"),\n            subtitle: Text(\"Yesterday\"),\n            amount: Text(2_450, format: .currency(code: \"KWD\")),\n            systemImage: \"building.columns.fill\",\n            tone: .positive\n        )\n    ],\n    onSelect: { id in }\n)",
            dependencies: ["metric-card", "transaction-row", "empty"],
            tags: ["finance", "dashboard", "overview", "transactions"]
        ),
        CatalogEntry(
            name: "input",
            kind: "component",
            version: "0.5.0",
            description: "Styles native TextField and SecureField controls with semantic fill, focus, disabled, and invalid treatments.",
            usage: "@State private var email = \"\"\n@State private var password = \"\"\n\n// The title is placeholder text to VoiceOver; the explicit label names\n// the field once it holds text.\nTextField(\"Email\", text: $email)\n    .textFieldStyle(.registryInput)\n    .accessibilityLabel(\"Email\")\n\nSecureField(\"Password\", text: $password)\n    .textFieldStyle(.registryInput)\n    .accessibilityLabel(\"Password\")\n\nTextField(\"Email\", text: $email)\n    .textFieldStyle(RegistryInputStyle(isInvalid: true))\n    .accessibilityLabel(\"Email\")\n    .accessibilityHint(\"Enter a valid email address\")",
            dependencies: [],
            tags: ["input", "text-field", "secure-field", "form", "style"]
        ),
        CatalogEntry(
            name: "input-group",
            kind: "component",
            version: "0.2.0",
            description: "Wraps a native text field with registry input chrome and caller-provided leading and trailing accessories, such as a search symbol and a clear button.",
            usage: "@State private var query = \"\"\n\nInputGroup {\n    Image(systemName: \"magnifyingglass\")\n        .accessibilityHidden(true)\n} content: {\n    TextField(\"Search transactions\", text: $query)\n        .accessibilityLabel(\"Search transactions\")\n} trailing: {\n    if !query.isEmpty {\n        Button(\"Clear search\", systemImage: \"xmark.circle.fill\") { query = \"\" }\n            .labelStyle(.iconOnly)\n            .buttonStyle(.registryGhost)\n            .controlSize(.small)\n    }\n}",
            dependencies: ["button"],
            tags: ["input", "group", "search", "accessory", "text-field", "shadcn"]
        ),
        CatalogEntry(
            name: "item",
            kind: "component",
            version: "0.2.0",
            description: "Composes a generic content row with leading media, a title and optional description, and a trailing accessory while leaving selection to the call site.",
            usage: "ItemRow(\n    title: Text(\"Statement ready\"),\n    description: Text(\"August 2026\")\n) {\n    Avatar(initials: \"ST\", accessibilityLabel: Text(\"Statements\"))\n} accessory: {\n    Text(\"New\").registryBadge()\n}",
            dependencies: ["avatar", "separator", "badge"],
            tags: ["item", "row", "list", "cell", "media", "shadcn"]
        ),
        CatalogEntry(
            name: "kbd",
            kind: "component",
            version: "0.1.1",
            description: "Draws text as a keycap for keyboard shortcut hints, hidden from accessibility unless a spoken label is supplied.",
            usage: "Text(verbatim: \"⌘K\")\n    .registryKeycap(accessibilityLabel: Text(\"Command K\"))\n\nText(verbatim: \"esc\")\n    .registryKeycap()",
            dependencies: [],
            tags: ["keyboard", "shortcut", "keycap", "hint", "shadcn"]
        ),
        CatalogEntry(
            name: "label",
            kind: "component",
            version: "0.2.0",
            description: "Controls native Label icon placement with semantic spacing and decorative icon accessibility behavior.",
            usage: "Label(\"Account settings\", systemImage: \"person.crop.circle\")\n    .labelStyle(.registry)\n\nLabel(\"Continue\", systemImage: \"chevron.forward\")\n    .labelStyle(.registryTrailingIcon)",
            dependencies: [],
            tags: ["label", "icon", "text", "alignment", "style"]
        ),
        CatalogEntry(
            name: "macro-progress",
            kind: "component",
            version: "0.3.0",
            description: "Displays prepared nutrition progress with a native progress view and adaptive value layout.",
            usage: "MacroProgress(\n    \"Protein\",\n    value: Text(\"96 g\"),\n    target: Text(\"130 g\"),\n    progress: 96.0 / 130.0,\n    systemImage: \"fish.fill\",\n    tint: .indigo\n)",
            dependencies: [],
            tags: ["nutrition", "health", "progress", "macronutrients"]
        ),
        CatalogEntry(
            name: "metric-card",
            kind: "component",
            version: "0.2.1",
            description: "Displays one prepared product metric using native text formatting and semantic styling.",
            usage: "MetricCard(\n    \"Available balance\",\n    value: Text(12_480.32, format: .currency(code: \"USD\")),\n    detail: Text(\"Up 8.2% this month\"),\n    systemImage: \"creditcard.fill\"\n)",
            dependencies: [],
            tags: ["metric", "finance", "health", "analytics"]
        ),
        CatalogEntry(
            name: "native-select",
            kind: "recipe",
            version: "0.3.0",
            description: "Native guidance for the minimal menu treatment of a bound SwiftUI Picker.",
            usage: "@State private var sort = \"recent\"\n\nPicker(\"Sort\", selection: $sort) {\n    Text(\"Most recent\").tag(\"recent\")\n    Text(\"Oldest\").tag(\"oldest\")\n    Text(\"Amount\").tag(\"amount\")\n}\n.pickerStyle(.menu)",
            dependencies: [],
            tags: ["native-select", "picker", "menu", "selection", "guidance"]
        ),
        CatalogEntry(
            name: "nutrition-overview",
            kind: "block",
            version: "0.2.1",
            description: "Composes prepared energy and macronutrient values into an embeddable nutrition overview.",
            usage: "NutritionOverview(\n    \"Today\",\n    energyTitle: \"Energy\",\n    energy: Text(\"1,640 kcal\"),\n    energyDetail: Text(\"360 kcal remaining\"),\n    sectionTitle: \"Macronutrients\",\n    macros: [\n        NutritionMacroItem(\n            id: \"protein\",\n            name: \"Protein\",\n            value: Text(\"96 g\"),\n            target: Text(\"130 g\"),\n            progress: 96.0 / 130.0,\n            systemImage: \"fish.fill\",\n            tint: .indigo\n        )\n    ],\n    actionTitle: \"Log food\",\n    onLogFood: {}\n)",
            dependencies: ["metric-card", "macro-progress"],
            tags: ["nutrition", "health", "dashboard", "overview", "macronutrients"]
        ),
        CatalogEntry(
            name: "popover",
            kind: "recipe",
            version: "0.1.0",
            description: "Native guidance for anchored, transient content with .popover, which adapts to a sheet on compact widths.",
            usage: "@State private var isShowingHelp = false\n\nButton(\"Why is this needed?\") { isShowingHelp = true }\n    .buttonStyle(.registryLink)\n    .popover(isPresented: $isShowingHelp) {\n        Text(\"We use your date of birth to verify your identity.\")\n            .padding()\n            .presentationCompactAdaptation(.popover)\n    }",
            dependencies: [],
            tags: ["popover", "hover-card", "tooltip", "anchored", "guidance"]
        ),
        CatalogEntry(
            name: "progress",
            kind: "component",
            version: "0.2.0",
            description: "Styles native determinate and indeterminate ProgressView controls with linear accent, positive, and negative semantic tones.",
            usage: "ProgressView(value: 0.68) {\n    Text(\"Uploading\")\n} currentValueLabel: {\n    Text(\"68 percent\")\n}\n.progressViewStyle(.registryLinear)\n\nProgressView(value: 1) {\n    Text(\"Import complete\")\n}\n.progressViewStyle(.registryLinearPositive)",
            dependencies: [],
            tags: ["progress", "progress-view", "linear", "loading", "style"]
        ),
        CatalogEntry(
            name: "radio-group",
            kind: "recipe",
            version: "0.3.0",
            description: "Native guidance for presenting a bound Picker as an inline mutually exclusive option group.",
            usage: "@State private var selection = \"standard\"\n\nPicker(\"Delivery speed\", selection: $selection) {\n    Text(\"Standard\").tag(\"standard\")\n    Text(\"Express\").tag(\"express\")\n    Text(\"Same day\").tag(\"same-day\")\n}\n.pickerStyle(.inline)",
            dependencies: [],
            tags: ["radio-group", "picker", "selection", "options", "guidance"]
        ),
        CatalogEntry(
            name: "scroll-area",
            kind: "recipe",
            version: "0.1.0",
            description: "Native guidance for scrollable content with content margins, indicator visibility, and clipping left to ScrollView.",
            usage: "ScrollView {\n    FinanceOverview(\n        \"Overview\",\n        balanceTitle: \"Available balance\",\n        balance: Text(12_480.32, format: .currency(code: \"USD\")),\n        changeTitle: \"Monthly change\",\n        change: Text(0.082, format: .percent),\n        sectionTitle: \"Recent activity\",\n        transactions: rows,\n        onSelect: { id in }\n    )\n}\n.contentMargins(.horizontal, 16, for: .scrollContent)\n.scrollIndicators(.hidden)\n.scrollClipDisabled()",
            dependencies: [],
            tags: ["scroll", "scroll-view", "margins", "indicators", "guidance"]
        ),
        CatalogEntry(
            name: "select",
            kind: "component",
            version: "0.2.0",
            description: "Adds semantic field chrome to a native menu-style Picker without replacing its presentation or selection behavior.",
            usage: "@State private var currency = \"KWD\"\n\nPicker(\"Currency\", selection: $currency) {\n    Text(\"Kuwaiti dinar\").tag(\"KWD\")\n    Text(\"US dollar\").tag(\"USD\")\n}\n.registrySelect()",
            dependencies: [],
            tags: ["select", "picker", "menu", "form", "modifier"]
        ),
        CatalogEntry(
            name: "separator",
            kind: "component",
            version: "0.2.0",
            description: "Applies semantic color, orientation, and caller-provided insets to a native Divider.",
            usage: "Divider()\n    .registrySeparator(insets: EdgeInsets(top: 0, leading: 16, bottom: 0, trailing: 16))\n\nDivider()\n    .registrySeparator(.vertical)",
            dependencies: [],
            tags: ["separator", "divider", "layout", "inset", "modifier"]
        ),
        CatalogEntry(
            name: "settings-section",
            kind: "block",
            version: "0.1.1",
            description: "Composes registry select, separator, and button treatments into a titled settings section that renders structure, separators, and per-row messages around caller-owned native toggle, picker, and action rows.",
            usage: "SettingsSection(\n    \"Notifications\",\n    footer: Text(\"Quiet hours apply to every channel.\")\n) {\n    Toggle(\"Transaction alerts\", isOn: $alertsEnabled)\n        .settingsRowDescription(Text(\"A push notification for every card transaction.\"))\n\n    Toggle(\"Marketing messages\", isOn: $marketingEnabled)\n        .settingsRowDisabled(\n            !marketingAllowed,\n            explanation: Text(\"Managed by your organization's privacy policy.\")\n        )\n\n    LabeledContent(\"Currency\") {\n        Picker(\"Currency\", selection: $currency) {\n            Text(\"Kuwaiti dinar\").tag(\"KWD\")\n            Text(\"US dollar\").tag(\"USD\")\n        }\n        .registrySelect()\n    }\n\n    Button(\"Sign out\", role: .destructive) { }\n        .buttonStyle(.registry)\n}",
            dependencies: ["select", "separator", "button"],
            tags: ["settings", "preferences", "section", "toggle", "form"]
        ),
        CatalogEntry(
            name: "sidebar",
            kind: "recipe",
            version: "0.1.0",
            description: "Native guidance for a sidebar layout with NavigationSplitView and a selection-bound List on iPad.",
            usage: "@State private var selection: String? = \"activity\"\n\nNavigationSplitView {\n    List(selection: $selection) {\n        Label(\"Activity\", systemImage: \"bell\").tag(\"activity\")\n        Label(\"Cards\", systemImage: \"creditcard\").tag(\"cards\")\n    }\n    .navigationTitle(\"Bank\")\n} detail: {\n    if selection == \"activity\" { ActivityScreen() } else { CardsScreen() }\n}",
            dependencies: [],
            tags: ["sidebar", "navigation", "split-view", "ipad", "guidance"]
        ),
        CatalogEntry(
            name: "skeleton",
            kind: "component",
            version: "0.2.0",
            description: "Turns any view into a loading placeholder with native redaction, disabled interaction, one loading accessibility element, and a pulse that stops under Reduce Motion.",
            usage: "@State private var isLoading = true\n\nActivityRows()\n    .registrySkeleton(isLoading)\n\n// Pass false to render the real content unchanged.",
            dependencies: [],
            tags: ["skeleton", "loading", "placeholder", "redacted", "shimmer", "shadcn"]
        ),
        CatalogEntry(
            name: "slider",
            kind: "recipe",
            version: "0.3.0",
            description: "Native guidance for a Slider with semantic tint, control sizing, and caller-owned value and labels.",
            usage: "@State private var volume = 64.0\n\nSlider(value: $volume, in: 0...100, step: 1) {\n    Text(\"Volume\")\n} minimumValueLabel: {\n    Image(systemName: \"speaker.fill\")\n        .accessibilityHidden(true)\n} maximumValueLabel: {\n    Image(systemName: \"speaker.wave.3.fill\")\n        .accessibilityHidden(true)\n}\n.controlSize(.large)",
            dependencies: [],
            tags: ["slider", "value", "range", "control", "guidance"]
        ),
        CatalogEntry(
            name: "spinner",
            kind: "component",
            version: "0.2.0",
            description: "Styles a native indeterminate ProgressView with a compact circular indicator and optional label.",
            usage: "ProgressView(\"Loading results\")\n    .progressViewStyle(.registrySpinner)",
            dependencies: [],
            tags: ["spinner", "progress-view", "circular", "loading", "style"]
        ),
        CatalogEntry(
            name: "switch",
            kind: "recipe",
            version: "0.3.0",
            description: "Native guidance for applying the platform switch treatment to a Toggle while inheriting app tint and environment behavior.",
            usage: "@State private var notifications = true\n\nToggle(\"Notifications\", isOn: $notifications)\n    .toggleStyle(.switch)",
            dependencies: [],
            tags: ["switch", "toggle", "setting", "boolean", "guidance"]
        ),
        CatalogEntry(
            name: "tabs",
            kind: "recipe",
            version: "0.3.0",
            description: "Native guidance for a local-selection Picker with the platform segmented style while leaving app navigation to TabView.",
            usage: "@State private var selection = \"overview\"\n\nPicker(\"Section\", selection: $selection) {\n    Text(\"Overview\").tag(\"overview\")\n    Text(\"Activity\").tag(\"activity\")\n    Text(\"Settings\").tag(\"settings\")\n}\n.pickerStyle(.segmented)",
            dependencies: [],
            tags: ["tabs", "picker", "segmented", "selection", "guidance"]
        ),
        CatalogEntry(
            name: "textarea",
            kind: "component",
            version: "0.4.0",
            description: "Applies input-matching focus, disabled, and invalid chrome to a native TextEditor.",
            usage: "@State private var notes = \"\"\n\nTextEditor(text: $notes)\n    .registryTextArea(accessibilityLabel: Text(\"Delivery instructions\"))",
            dependencies: [],
            tags: ["textarea", "text-editor", "multiline", "form", "modifier"]
        ),
        CatalogEntry(
            name: "toggle",
            kind: "component",
            version: "0.2.0",
            description: "Applies registry button treatments to native Toggle state for compact selectable controls.",
            usage: "// Content layer only. In toolbars, tab bars, or floating chrome the system supplies Liquid Glass; use .buttonStyle(.glass) or .buttonStyle(.glassProminent) there instead of .registry styles.\n\n@State private var bold = false\n\nToggle(\"Bold\", systemImage: \"bold\", isOn: $bold)\n    .toggleStyle(.registryToggle)",
            dependencies: ["button"],
            tags: ["toggle", "button", "selection", "formatting", "style"]
        ),
        CatalogEntry(
            name: "toggle-group",
            kind: "component",
            version: "0.2.0",
            description: "Applies one registry toggle treatment to native Toggle controls in a caller-owned ControlGroup.",
            usage: "// Content layer only. In toolbars, tab bars, or floating chrome the system supplies Liquid Glass; use .buttonStyle(.glass) or .buttonStyle(.glassProminent) there instead of .registry styles.\n\n@State private var bold = false\n@State private var italic = false\n\nControlGroup {\n    Toggle(\"Bold\", systemImage: \"bold\", isOn: $bold)\n    Toggle(\"Italic\", systemImage: \"italic\", isOn: $italic)\n}\n.registryToggleGroup()",
            dependencies: ["toggle", "button"],
            tags: ["toggle-group", "toggle", "control-group", "multi-selection", "modifier"]
        ),
        CatalogEntry(
            name: "tooltip",
            kind: "recipe",
            version: "0.1.0",
            description: "Native guidance for supplementary help without hover: an accessibility hint plus an optional informational popover.",
            usage: "Button(\"Freeze card\", systemImage: \"snowflake\") { }\n    .buttonStyle(.registryOutline)\n    .accessibilityHint(\"Blocks new purchases until you unfreeze the card.\")\n    .help(\"Blocks new purchases until you unfreeze the card.\")",
            dependencies: [],
            tags: ["tooltip", "help", "hint", "hover", "guidance"]
        ),
        CatalogEntry(
            name: "transaction-row",
            kind: "component",
            version: "0.4.1",
            description: "Displays prepared transaction content while leaving selection to a native Button at the call site.",
            usage: "TransactionRow(\n    title: Text(\"Mishmash Bakery\"),\n    subtitle: Text(\"Today, 09:41\"),\n    amount: Text(-8.75, format: .currency(code: \"KWD\")),\n    systemImage: \"cup.and.saucer.fill\",\n    tone: .negative\n)",
            dependencies: [],
            tags: ["transaction", "row", "finance", "activity"]
        ),
    ]

    static func entry(named name: String) -> CatalogEntry? {
        entries.first { $0.name == name }
    }

    static func entries(ofKind kind: String) -> [CatalogEntry] {
        entries.filter { $0.kind == kind }
    }
}
