// Generated by `swiftui-registry generate usage-checks` from Registry metadata.
// Do not edit by hand; edit the item document and regenerate.
//
// Each struct compiles one installable item's `usage` snippet, so a snippet
// that names an undeclared symbol fails the Showcase build instead of
// shipping. A symbol a snippet treats as the consumer's own code is a
// stand-in declared in `UsageSnippetPlaceholders.swift`.
import Charts
import SwiftUI
import SwiftUIRegistryFoundations

// MARK: accordion
private struct UsageSnippet_Accordion: View {
    @State private var isExpanded = false
    var body: some View {
        DisclosureGroup("How do I freeze my card?", isExpanded: $isExpanded) {
            Text("Open the card, then choose Freeze.")
        }
        .disclosureGroupStyle(.registryAccordion)
    }
}

// MARK: activity-feed
private struct UsageSnippet_ActivityFeed: View {
    var body: some View {
        ActivityFeed(
            "Activity",
            notice: ActivityNotice("Card delivery delayed", message: Text("Arrives Thursday.")),
            onDismissNotice: { },
            items: [
                ActivityItem(
                    id: "bakery",
                    title: Text("Mishmash Bakery"),
                    detail: Text("Card payment of KWD 8.750"),
                    timestamp: Text("09:41"),
                    initials: "MB",
                    senderName: Text("Mishmash Bakery"),
                    isUnread: true
                )
            ],
            earlierItems: [],
            isLoading: false,
            onSelect: { id in }
        )
    }
}

// MARK: alert
private struct UsageSnippet_Alert: View {
    var body: some View {
        InlineAlert(
            "Card delivery delayed",
            message: Text("Your new card now arrives on Thursday.")
        )
        InlineAlert(
            "Payment failed",
            message: Text("The card on file was declined.")
        ) {
            Button("Retry") {}
                .buttonStyle(.registry)
        }
        .registryVariant(.destructive)
    }
}

// MARK: attachment
private struct UsageSnippet_Attachment: View {
    var body: some View {
        AttachmentRow(
            name: Text("Statement-Aug-2026.pdf"),
            detail: Text("PDF document, 1.2 MB"),
            state: .uploading(progress: 0.68)
        ) {
            Image(systemName: "doc.fill")
        } actions: {
            Button("Cancel", systemImage: "xmark") {}
                .labelStyle(.iconOnly)
                .buttonStyle(.registryGhost)
                .accessibilityLabel("Cancel upload")
        }
        // A completed attachment with a thumbnail and no actions: the bare trailing closure is the thumbnail.
        AttachmentRow(
            name: Text("Receipt.jpg"),
            detail: Text("Image, 240 KB"),
            state: .completed
        ) {
            Image(systemName: "photo")
        }
    }
}

// MARK: auth-form
private struct UsageSnippet_AuthForm: View {
    @State private var email = ""
    @State private var password = ""
    @State private var isSubmitting = false
    let formError: LocalizedStringResource? = nil
    // Errors derive from state; nil hides the message and clears the invalid style.
    var emailError: LocalizedStringResource? {
        email.isEmpty || email.contains("@") ? nil : "Enter a valid email address."
    }
    var passwordError: LocalizedStringResource? {
        password.isEmpty || password.count >= 8 ? nil : "Use at least 8 characters."
    }
    var body: some View {
        AuthForm(
            "Welcome back",
            identity: $email,
            identityError: emailError,
            password: $password,
            passwordError: passwordError,
            formError: formError,
            isSubmitting: isSubmitting,
            secondaryActionTitle: "Forgot password?",
            onSecondaryAction: { },
            onSubmit: { }
        )
    }
}

// MARK: avatar
private struct UsageSnippet_Avatar: View {
    var body: some View {
        Avatar(Image("maya"), accessibilityLabel: Text("Maya Khalid"))
        Avatar(initials: "MK", accessibilityLabel: Text("Maya Khalid"))
            .controlSize(.large)
        Avatar(accessibilityLabel: Text("Unknown sender"))
    }
}

// MARK: badge
private struct UsageSnippet_Badge: View {
    var body: some View {
        Text("New")
            .registryBadge()
        Label("Completed", systemImage: "checkmark.circle.fill")
            .registryBadge(.positive)
    }
}

// MARK: breadcrumb
private struct UsageSnippet_Breadcrumb: View {
    var body: some View {
        Breadcrumb([
            BreadcrumbItem(Text("Home"), action: { path = NavigationPath() }),
            BreadcrumbItem(Text("Library"), action: { path.removeLast() }),
            BreadcrumbItem(Text("Payments"))
        ])
    }
}

// MARK: bubble
private struct UsageSnippet_Bubble: View {
    var body: some View {
        Text("Are we still on for Thursday?")
            .registryBubble(.incoming)
        Text("Yes, 6pm works.")
            .registryBubble(.outgoing)
    }
}

// MARK: button
private struct UsageSnippet_Button: View {
    var body: some View {
        // Content layer only. In toolbars, tab bars, or floating chrome the system supplies Liquid Glass; use .buttonStyle(.glass) or .buttonStyle(.glassProminent) there instead of .registry styles.
        Button("Save changes") {}
            .buttonStyle(.registry)
        Button("Cancel") {}
            .buttonStyle(.registryOutline)
        Button("Delete", role: .destructive) {}
            .buttonStyle(.registry)
    }
}

// MARK: button-group
private struct UsageSnippet_ButtonGroup: View {
    var body: some View {
        // Content layer only. In toolbars, tab bars, or floating chrome the system supplies Liquid Glass; use .buttonStyle(.glass) or .buttonStyle(.glassProminent) there instead of .registry styles.
        ControlGroup {
            Button("Undo", systemImage: "arrow.uturn.backward") {}
            Button("Redo", systemImage: "arrow.uturn.forward") {}
        }
        .controlGroupStyle(.registryButtons)
    }
}

// MARK: card
private struct UsageSnippet_Card: View {
    var body: some View {
        GroupBox {
            Text("Manage billing and renewal details from your account settings.")
        } label: {
            Label("Subscription", systemImage: "creditcard.fill")
        }
        .groupBoxStyle(.registryCard)
    }
}

// MARK: chart
private struct UsageSnippet_Chart: View {
    var body: some View {
        Chart(data) { row in
            BarMark(
                x: .value("Month", row.month),
                y: .value("Visits", row.visits)
            )
            .foregroundStyle(by: .value("Channel", row.channel))
            .position(by: .value("Channel", row.channel))
        }
        .registryChart()
        .frame(height: 180)
    }
}

// MARK: checkbox
private struct UsageSnippet_Checkbox: View {
    @State private var accepted = false
    var body: some View {
        Toggle("Accept terms", isOn: $accepted)
            .toggleStyle(.registryCheckbox)
    }
}

// MARK: combobox
private struct UsageSnippet_Combobox: View {
    @State private var timezone: String? = "riyadh"
    var body: some View {
        Combobox(
            selection: $timezone,
            options: [
                ComboboxOption(id: "kuwait", title: "Kuwait City", systemImage: "clock"),
                ComboboxOption(id: "riyadh", title: "Riyadh", systemImage: "clock")
            ],
            prompt: "Search time zones",
            emptyDescription: Text("Try a city name.")
        )
    }
}

// MARK: command
private struct UsageSnippet_Command: View {
    @State private var query = ""
    var body: some View {
        CommandPalette(
            query: $query,
            prompt: "Search actions",
            sections: [
                CommandSection(id: "actions", title: "Actions", entries: [
                    CommandEntry(id: "transfer", title: Text("New transfer"), systemImage: "arrow.up.right", shortcut: "⌘T", shortcutLabel: Text("Command T"))
                ])
            ],
            onSelect: { id in }
        )
    }
}

// MARK: command-search
private struct UsageSnippet_CommandSearch: View {
    @State private var query = ""
    var body: some View {
        CommandSearch(
            "Search",
            query: $query,
            prompt: "Search actions and activity",
            sections: sections,
            emptyDescription: Text("Try a payee, a card, or an action."),
            shortcuts: [
                CommandShortcutHint("Open search", keys: "⌘K", keysLabel: Text("Command K"))
            ],
            onSelect: { id in }
        )
    }
}

// MARK: dashboard
private struct UsageSnippet_Dashboard: View {
    var body: some View {
        Dashboard(
            "Analytics",
            metrics: [
                DashboardMetric(
                    title: "Revenue",
                    value: Text(48_200, format: .currency(code: "USD")),
                    detail: Text("Up 12% this month"),
                    systemImage: "dollarsign.circle.fill"
                )
            ],
            chartTitle: "Visitors by channel",
            points: [
                DashboardSeriesPoint(id: "jan-direct", category: "Jan", series: "Direct", value: 186)
            ],
            tableTitle: "Recent invoices",
            rows: [
                DashboardRow(
                    id: "1041",
                    title: Text("Invoice 1041"),
                    detail: Text("Northwind Trading"),
                    status: Text("Paid"),
                    amount: Text(1_240, format: .currency(code: "USD"))
                )
            ],
            onSelect: { id in }
        )
    }
}

// MARK: empty
private struct UsageSnippet_Empty: View {
    var body: some View {
        ContentUnavailableView(
            "No recent activity",
            systemImage: "clock.arrow.circlepath",
            description: Text("New transactions will appear here.")
        )
        .registryEmptyState()
    }
}

// MARK: field
private struct UsageSnippet_Field: View {
    @State private var name = ""
    @State private var email = ""
    @State private var phone = ""
    @State private var showErrors = false
    @State private var phoneError: String? = nil
    var body: some View {
        FieldGroup {
            Field("Full name", description: "As it appears on your card.") { _ in
                TextField("Full name", text: $name)
                    .textFieldStyle(.registryInput)
                    .accessibilityLabel("Full name")
            }
            Field("Email", error: showErrors ? "Enter a valid email address." : nil) { isInvalid in
                TextField("you@example.com", text: $email)
                    .textFieldStyle(RegistryInputStyle(isInvalid: isInvalid))
                    .accessibilityLabel("Email")
            }
            Field("Phone", error: phoneError) { isInvalid in
                TextField("Phone", text: $phone)
                    .textFieldStyle(RegistryInputStyle(isInvalid: isInvalid))
                    .accessibilityLabel("Phone")
            }
        }
    }
}

// MARK: finance-overview
private struct UsageSnippet_FinanceOverview: View {
    var body: some View {
        FinanceOverview(
            "Overview",
            balanceTitle: "Available balance",
            balance: Text(12_480.32, format: .currency(code: "USD")),
            changeTitle: "Monthly change",
            change: Text(0.082, format: .percent),
            sectionTitle: "Recent activity",
            transactions: [
                FinanceTransactionItem(
                    id: "salary",
                    title: Text("Salary"),
                    subtitle: Text("Yesterday"),
                    amount: Text(2_450, format: .currency(code: "KWD")),
                    systemImage: "building.columns.fill",
                    tone: .positive
                )
            ],
            onSelect: { id in }
        )
    }
}

// MARK: input
private struct UsageSnippet_Input: View {
    @State private var email = ""
    @State private var password = ""
    var body: some View {
        // The title is placeholder text to VoiceOver; the explicit label names
        // the field once it holds text.
        TextField("Email", text: $email)
            .textFieldStyle(.registryInput)
            .accessibilityLabel("Email")
        SecureField("Password", text: $password)
            .textFieldStyle(.registryInput)
            .accessibilityLabel("Password")
        TextField("Email", text: $email)
            .textFieldStyle(RegistryInputStyle(isInvalid: true))
            .accessibilityLabel("Email")
            .accessibilityHint("Enter a valid email address")
    }
}

// MARK: input-group
private struct UsageSnippet_InputGroup: View {
    @State private var query = ""
    var body: some View {
        InputGroup {
            Image(systemName: "magnifyingglass")
                .accessibilityHidden(true)
        } content: {
            TextField("Search transactions", text: $query)
                .accessibilityLabel("Search transactions")
        } trailing: {
            if !query.isEmpty {
                Button("Clear search", systemImage: "xmark.circle.fill") { query = "" }
                    .labelStyle(.iconOnly)
                    .buttonStyle(.registryGhost)
                    .controlSize(.small)
            }
        }
    }
}

// MARK: item
private struct UsageSnippet_Item: View {
    var body: some View {
        ItemRow(
            title: Text("Statement ready"),
            description: Text("August 2026")
        ) {
            Avatar(initials: "ST", accessibilityLabel: Text("Statements"))
        } accessory: {
            Text("New").registryBadge()
        }
        // Media only: the bare trailing closure is the media; name accessory: to add a trailing accessory.
        ItemRow(title: Text("Mishmash Bakery"), description: Text("Card payment")) {
            Avatar(initials: "MB", accessibilityLabel: Text("Mishmash Bakery"))
        }
    }
}

// MARK: kbd
private struct UsageSnippet_Kbd: View {
    var body: some View {
        Text(verbatim: "⌘K")
            .registryKeycap(accessibilityLabel: Text("Command K"))
        Text(verbatim: "esc")
            .registryKeycap()
    }
}

// MARK: label
private struct UsageSnippet_Label: View {
    var body: some View {
        Label("Account settings", systemImage: "person.crop.circle")
            .labelStyle(.registry)
        Label("Continue", systemImage: "chevron.forward")
            .labelStyle(.registryTrailingIcon)
    }
}

// MARK: macro-progress
private struct UsageSnippet_MacroProgress: View {
    var body: some View {
        MacroProgress(
            "Protein",
            value: Text("96 g"),
            target: Text("130 g"),
            progress: 96.0 / 130.0,
            systemImage: "fish.fill"
        )
        .registryTint(.indigo)
    }
}

// MARK: marker
private struct UsageSnippet_Marker: View {
    var body: some View {
        Text("Today")
            .registryMarker(.separator)
        Text("Maya joined the conversation")
            .registryMarker()
        Text("Delivered 09:41")
            .registryMarker(.status)
    }
}

// MARK: message
private struct UsageSnippet_Message: View {
    var body: some View {
        MessageRow(
            author: Text("Maya"),
            timestamp: Text("09:41"),
            status: Text("Delivered")
        ) {
            Avatar(initials: "MK", accessibilityLabel: Text("Maya Khalid"))
        } content: {
            Text("Are we still on for Thursday?")
        }
        MessageRow {
            Text("Yes, 6pm works.")
        }
        .registryVariant(.outgoing)
    }
}

// MARK: message-scroller
private struct UsageSnippet_MessageScroller: View {
    // messages is your own model collection; each element is Identifiable
    // with an id, a text, and isMine.
    @State private var position: String?
    @State private var isFollowing = true
    var body: some View {
        MessageScroller(position: $position, isFollowing: $isFollowing) {
            ForEach(messages) { message in
                MessageRow {
                    Text(message.text)
                }
                .registryVariant(message.isMine ? .outgoing : .incoming)
                .id(message.id)
            }
        }
    }
}

// MARK: metric-card
private struct UsageSnippet_MetricCard: View {
    var body: some View {
        MetricCard(
            "Available balance",
            value: Text(12_480.32, format: .currency(code: "USD")),
            detail: Text("Up 8.2% this month"),
            systemImage: "creditcard.fill"
        )
    }
}

// MARK: nutrition-overview
private struct UsageSnippet_NutritionOverview: View {
    var body: some View {
        NutritionOverview(
            "Today",
            energyTitle: "Energy",
            energy: Text("1,640 kcal"),
            energyDetail: Text("360 kcal remaining"),
            sectionTitle: "Macronutrients",
            macros: [
                NutritionMacroItem(
                    id: "protein",
                    name: "Protein",
                    value: Text("96 g"),
                    target: Text("130 g"),
                    progress: 96.0 / 130.0,
                    systemImage: "fish.fill",
                    tint: .indigo
                )
            ],
            actionTitle: "Log food",
            onLogFood: {}
        )
    }
}

// MARK: preview
private struct UsageSnippet_Preview: View {
    var body: some View {
        PreviewWall()
    }
}

// MARK: preview-02
private struct UsageSnippet_Preview02: View {
    var body: some View {
        PreviewWall02()
    }
}

// MARK: progress
private struct UsageSnippet_Progress: View {
    var body: some View {
        ProgressView(value: 0.68) {
            Text("Uploading")
        } currentValueLabel: {
            Text("68 percent")
        }
        .progressViewStyle(.registryLinear)
        ProgressView(value: 1) {
            Text("Import complete")
        }
        .progressViewStyle(.registryLinearPositive)
    }
}

// MARK: questionnaire
private struct UsageSnippet_Questionnaire: View {
    @State private var currentStep = 0
    @State private var answers: [String: QuestionnaireAnswer] = [:]
    var body: some View {
        Questionnaire(
            "Set up your profile",
            steps: [
                QuestionnaireStep(
                    id: "goal",
                    title: "What is your main goal?",
                    kind: .singleChoice([
                        QuestionnaireOption(id: "save", title: "Save more"),
                        QuestionnaireOption(id: "invest", title: "Start investing")
                    ])
                )
            ],
            currentStep: $currentStep,
            answers: $answers,
            onFinish: { }
        )
    }
}

// MARK: select
private struct UsageSnippet_Select: View {
    @State private var currency = "KWD"
    var body: some View {
        Picker("Currency", selection: $currency) {
            Text("Kuwaiti dinar").tag("KWD")
            Text("US dollar").tag("USD")
        }
        .registrySelect()
    }
}

// MARK: separator
private struct UsageSnippet_Separator: View {
    var body: some View {
        Divider()
            .registrySeparator(insets: EdgeInsets(top: 0, leading: 16, bottom: 0, trailing: 16))
        Divider()
            .registrySeparator(.vertical)
    }
}

// MARK: settings-section
private struct UsageSnippet_SettingsSection: View {
    @State private var alertsEnabled = true
    @State private var marketingEnabled = false
    @State private var currency = "KWD"
    let marketingAllowed = false
    var body: some View {
        SettingsSection(
            "Notifications",
            footer: Text("Quiet hours apply to every channel.")
        ) {
            Toggle("Transaction alerts", isOn: $alertsEnabled)
                .settingsRowDescription(Text("A push notification for every card transaction."))
        
            Toggle("Marketing messages", isOn: $marketingEnabled)
                .settingsRowDisabled(
                    !marketingAllowed,
                    explanation: Text("Managed by your organization's privacy policy.")
                )
        
            LabeledContent("Currency") {
                Picker("Currency", selection: $currency) {
                    Text("Kuwaiti dinar").tag("KWD")
                    Text("US dollar").tag("USD")
                }
                .registrySelect()
            }
        
            Button("Sign out", role: .destructive) { }
                .buttonStyle(.registry)
        }
    }
}

// MARK: signup-form
private struct UsageSnippet_SignupForm: View {
    @State private var name = ""
    @State private var email = ""
    @State private var password = ""
    @State private var confirmation = ""
    @State private var acceptsTerms = false
    @State private var isSubmitting = false
    let formError: LocalizedStringResource? = nil
    // Errors derive from state; nil hides the message and clears the invalid style.
    var nameError: LocalizedStringResource? { nil }
    var emailError: LocalizedStringResource? {
        email.isEmpty || email.contains("@") ? nil : "Enter a valid email address."
    }
    var passwordError: LocalizedStringResource? {
        password.isEmpty || password.count >= 8 ? nil : "Use at least 8 characters."
    }
    var confirmationError: LocalizedStringResource? {
        confirmation == password ? nil : "Passwords do not match."
    }
    var termsError: LocalizedStringResource? { nil }
    var body: some View {
        SignUpForm(
            "Create your account",
            name: $name,
            nameError: nameError,
            email: $email,
            emailError: emailError,
            password: $password,
            passwordError: passwordError,
            confirmation: $confirmation,
            confirmationError: confirmationError,
            acceptsTerms: $acceptsTerms,
            termsError: termsError,
            formError: formError,
            isSubmitting: isSubmitting,
            secondaryActionTitle: "Already have an account?",
            onSecondaryAction: { },
            onSubmit: { }
        )
    }
}

// MARK: skeleton
private struct UsageSnippet_Skeleton: View {
    @State private var isLoading = true
    var body: some View {
        ActivityRows()
            .registrySkeleton(isLoading)
        // Pass false to render the real content unchanged.
    }
}

// MARK: spinner
private struct UsageSnippet_Spinner: View {
    var body: some View {
        ProgressView("Loading results")
            .progressViewStyle(.registrySpinner)
    }
}

// MARK: table
private struct UsageSnippet_Table: View {
    var body: some View {
        DataTable(
            lines,
            columns: [
                DataTableColumn(Text("Item")) { Text($0.item) },
                DataTableColumn(Text("Qty"), alignment: .trailing) { Text($0.quantity, format: .number) },
                DataTableColumn(Text("Amount"), alignment: .trailing) { Text($0.amount, format: .currency(code: "USD")) }
            ],
            footer: [
                DataTableFooterRow(label: Text("Total due"), value: Text(total, format: .currency(code: "USD")), isEmphasized: true)
            ]
        )
    }
}

// MARK: textarea
private struct UsageSnippet_Textarea: View {
    @State private var notes = ""
    var body: some View {
        TextEditor(text: $notes)
            .registryTextArea(accessibilityLabel: Text("Delivery instructions"))
    }
}

// MARK: toast
private struct UsageSnippet_Toast: View {
    @State private var toast: RegistryToast?
    var body: some View {
        CardDetail()
            .registryToast($toast)
    }
    private func statements() {
        // Present a destructive toast with an undo action:
        toast = RegistryToast(
            title: "Message deleted",
            message: "You can undo this for a few seconds.",
            variant: .destructive,
            action: RegistryToast.Action(label: "Undo") { restoreMessage() }
        )
    }
}

// MARK: toggle
private struct UsageSnippet_Toggle: View {
    // Content layer only. In toolbars, tab bars, or floating chrome the system supplies Liquid Glass; use .buttonStyle(.glass) or .buttonStyle(.glassProminent) there instead of .registry styles.
    @State private var bold = false
    var body: some View {
        Toggle("Bold", systemImage: "bold", isOn: $bold)
            .toggleStyle(.registryToggle)
    }
}

// MARK: toggle-group
private struct UsageSnippet_ToggleGroup: View {
    // Content layer only. In toolbars, tab bars, or floating chrome the system supplies Liquid Glass; use .buttonStyle(.glass) or .buttonStyle(.glassProminent) there instead of .registry styles.
    @State private var bold = false
    @State private var italic = false
    var body: some View {
        ControlGroup {
            Toggle("Bold", systemImage: "bold", isOn: $bold)
            Toggle("Italic", systemImage: "italic", isOn: $italic)
        }
        .registryToggleGroup()
    }
}

// MARK: transaction-row
private struct UsageSnippet_TransactionRow: View {
    var body: some View {
        TransactionRow(
            title: Text("Mishmash Bakery"),
            subtitle: Text("Today, 09:41"),
            amount: Text(-8.75, format: .currency(code: "KWD")),
            systemImage: "cup.and.saucer.fill"
        )
        .registryTone(.negative)
    }
}
