import Dependencies
import Foundation

public struct CatalogGenerator {
  let registry: Registry
  @Dependency(\.registryFileSystem) var fs
  public init(root: String) throws { registry = try Registry(root: root) }
  private let note =
    "<!-- Generated by `swiftui-registry generate catalog` from Registry metadata. Do not edit by hand; edit the item document and regenerate. -->"
  private let destinationNote =
    "Point `--destination` at a folder inside the consuming target's sources, such as `Sources/YourFeature/Components`, so the copied files are members of that build target"

  public func generate(output: String) throws -> [String] {
    guard registry.items["index"] == nil else {
      throw RegistryError(
        "An item named 'index' would collide with the catalog index page; rename the item")
    }
    try fs.createDirectory(output)
    var written: [String] = []
    for name in registry.items.keys.sorted() {
      let path = output + "/" + name + ".md"
      try fs.write(Data(try itemPage(name).utf8), to: path)
      written.append(path)
    }
    let index = output + "/index.md"
    try fs.write(Data(indexPage().utf8), to: index)
    written.append(index)
    for stale in try fs.children(output) where stale.hasSuffix(".md") && !written.contains(stale) {
      try fs.remove(stale)
    }
    return written
  }
  func indexPage() -> String {
    var lines = [
      note, "", "# SwiftUIRegistry catalog", "",
      "\(registry.items.count) items you copy into your app and own. The `swiftui-registry` tool comes from a clone of the registry repository: run `swift run swiftui-registry <command>` from the root of that clone, or build it once with `swift build -c release` and pass `--registry <path to the clone>` from anywhere. Components and blocks install with one command:",
      "", "```sh",
      "swiftui-registry install <name> --destination Sources/YourFeature/Components", "```", "",
      destinationNote, "",
    ]
    for (kind, heading, summary) in [
      ("block", "Blocks", "Compositions of components. Installing one installs its whole closure"),
      ("component", "Components", "One installable style, modifier, or view each"),
      ("flow", "Flows", "Multi-screen compositions"),
      ("recipe", "Recipes", "Native guidance. Nothing installs; copy the snippet"),
    ] {
      let names = registry.items.keys.filter { registry.items[$0]!["kind"].text == kind }.sorted()
      if names.isEmpty { continue }
      lines += ["## \(heading) (\(names.count))", "", summary, ""]
      lines += names.map { "- [\($0)](\($0).md): \(registry.items[$0]!["description"].text)" }
      lines.append("")
    }
    return finish(lines)
  }
  func itemPage(_ name: String) throws -> String {
    let item = registry.items[name]!
    let recipe = item["kind"] == "recipe"
    let preview = item["preview"]
    var lines = [note, "", "# \(name)", "", item["description"].text, ""]
    let screenshots = preview["screenshots"].strings
    if let first = screenshots.first {
      lines += ["![\(name) preview](\(relativeLink(first)))", ""]
      let alternatives = screenshots.dropFirst().map { path in
        var label = ((path as NSString).lastPathComponent as NSString).deletingPathExtension
        if label.hasPrefix(name + "-") { label.removeFirst(name.count + 1) }
        return "[\(label.replacingOccurrences(of: "-", with: " "))](\(relativeLink(path)))"
      }
      if !alternatives.isEmpty {
        lines += ["More previews: " + alternatives.joined(separator: ", "), ""]
      }
    }
    if recipe {
      lines += ["Nothing to install. Copy the snippet below", ""]
    } else {
      lines += [
        "## Install", "", "```sh",
        "swiftui-registry install \(name) --destination Sources/YourFeature/Components", "```",
        "", destinationNote, "",
      ]
      lines += try requirementLines(registry.packageRequirements(name))
      lines += [
        "Verify the install by building the consuming target for an iOS Simulator destination", "",
      ]
    }
    lines += ["## Usage", "", "```swift"] + pythonLines(item["usage"].text) + ["```", ""]
    if recipe { lines += ["## Why native is enough", ""] + pythonLines(item["docs"].text) + [""] }
    let platforms = (item["platforms"].array ?? []).map {
      "\($0["name"].text) \($0["minimumVersion"].text)+"
    }.joined(separator: ", ")
    lines += [
      "## Details", "", "- Kind: \(item["kind"].text)", "- Version: \(item["version"].text)",
      "- Platforms: \(platforms)",
    ]
    if !recipe {
      let closure = try registry.resolve(name)
      lines.append(
        closure == [name]
          ? "- Registry dependencies: none"
          : "- Installs in order: "
            + closure.map { "[\($0)](\($0).md) \(registry.items[$0]!["version"].text)" }.joined(
              separator: ", "))
    }
    let accessibility = item["accessibility"].strings
    lines +=
      accessibility.isEmpty
      ? ["- Accessibility contract: none declared"]
      : ["- Accessibility contract:"] + accessibility.map { "  - \($0)" }
    let sources = (item["files"].array ?? []).map { file in
      let source = file["source"].text
      return "[\(source)](\(relativeLink("Registry/" + source)))"
        + (source == preview["source"].text
          ? ", with the `\(preview["name"].text)` Xcode preview" : "")
    }
    if sources.count == 1 {
      lines += ["- Source: " + sources[0]]
    } else if !sources.isEmpty {
      lines += ["- Source:"] + sources.map { "  - " + $0 }
    }
    return finish(lines)
  }
  private func requirementLines(_ requirements: [JSON]) -> [String] {
    if requirements.isEmpty {
      return ["Nothing else to add; this item has no package requirement", ""]
    }
    var lines =
      requirements.count == 1
      ? ["Then " + Registry.dependencyInstruction(requirements[0]), ""]
      : ["Then add each package requirement to that target:", ""]
        + requirements.map { "- " + Registry.dependencyInstruction($0) } + [""]
    for entry in requirements {
      let snippet = Registry.dependencyManifest(entry)
      if !snippet.isEmpty {
        lines += ["```swift"] + snippet + ["```", "", Registry.dependencyXcode(entry), ""]
      }
    }
    return lines
  }
  private func finish(_ lines: [String]) -> String {
    lines.joined(separator: "\n").trimmingCharacters(in: CharacterSet(charactersIn: "\n")) + "\n"
  }
  private func relativeLink(_ path: String) -> String {
    var parts = [String]()
    for part in path.split(separator: "/") {
      if part == "." { continue }
      if part == "..", !parts.isEmpty { parts.removeLast() } else { parts.append(String(part)) }
    }
    var home = ["docs", "catalog"]
    while !home.isEmpty && home.first == parts.first {
      home.removeFirst()
      parts.removeFirst()
    }
    return (Array(repeating: "..", count: home.count) + parts).joined(separator: "/")
  }
}

func pythonLines(_ text: String) -> [String] {
  // str.splitlines() treats CRLF as one boundary and omits the final empty line.
  let normalized = text.replacingOccurrences(of: "\r\n", with: "\n")
  var lines = normalized.components(
    separatedBy: CharacterSet(
      charactersIn: "\n\r\u{0b}\u{0c}\u{1c}\u{1d}\u{1e}\u{85}\u{2028}\u{2029}"))
  if lines.last == "" { lines.removeLast() }
  return lines
}
