import Dependencies
import Foundation

/// The item-to-token map the design surface scopes its panel by: for every
/// catalog item, the theme fields its sources and its dependency closure read,
/// and for a recipe, what its usage snippet uses. Derived from the sources,
/// never declared by hand, so the map cannot drift from what an item draws with.
public struct ItemTokensGenerator {
  let registry: Registry
  @Dependency(\.registryFileSystem) var fs
  public static let outputPath = "Sources/SwiftUIRegistryDesignSurface/RegistryItemTokens.swift"
  public init(root: String) throws { registry = try Registry(root: root) }
  private let header = #"""
    // Generated by `swiftui-registry generate item-tokens` from Registry sources.
    // Do not edit by hand; edit the item source and regenerate.

    #if canImport(UIKit)
    /// The `RegistryTheme` and `RegistryMetrics` fields each catalog item
    /// reads, over its dependency closure, so the design surface can scope its
    /// panel to the knobs that move a selected item. A recipe reads what its
    /// usage snippet uses, which for a native one is nothing scoped: the accent
    /// and the typography still reach it through the root modifier.
    public enum RegistryItemTokens {
        public static let tokens: [String: [String]] = [

    """# + "\n"
  private let footer = #"""
        ]

        /// The tokens an item reads, or `nil` for a name the registry does not know.
        public static func tokens(for item: String) -> [String]? {
            tokens[item]
        }
    }
    #endif
    """# + "\n"

  /// The fields a source reads: `theme.<field>` and `theme.metrics.<field>`
  /// references, plus what the foundations calls it makes read in turn.
  static func tokens(in source: String) -> Set<String> {
    var found: Set<String> = []
    for match in source.matches(of: /theme\.(?:metrics\.)?([A-Za-z]+)/) {
      let field = String(match.1)
      if field != "metrics" { found.insert(field) }
    }
    if source.contains("registrySurface(") {
      found.formUnion(["surface", "border", "cardRadius", "borderWidth"])
    }
    if source.contains("surface(at:") || source.contains("registrySurface(level:") {
      found.formUnion(["surfaceOpacity", "surfaceStep"])
    }
    return found
  }

  public func tokens(for name: String) throws -> [String] {
    var found: Set<String> = []
    // A recipe installs nothing, so it has no sources: the code a consumer
    // copies is its usage snippet, and what that snippet uses is what it reads.
    if registry.items[name]?["kind"] == "recipe" {
      let item = registry.items[name]!
      found.formUnion(Self.tokens(in: item["usage"].text))
      for dependency in item["registryDependencies"].strings {
        found.formUnion(try tokens(for: dependency))
      }
      return found.sorted()
    }
    for member in try registry.resolve(name) {
      for file in registry.items[member]!["files"].array ?? [] {
        let text = try readText(fs, registry.root + "/Registry/" + file["source"].text)
        found.formUnion(Self.tokens(in: text))
      }
    }
    return found.sorted()
  }

  public func render() throws -> String {
    var result = header
    for name in registry.items.keys.sorted() {
      let kind = registry.items[name]!["kind"].text
      guard kind == "component" || kind == "block" || kind == "recipe" else { continue }
      let fields = try tokens(for: name).map(ShowcaseManifestGenerator.swiftString)
      result +=
        "            \(ShowcaseManifestGenerator.swiftString(name)): [\(fields.joined(separator: ", "))],\n"
    }
    return result + footer
  }

  public func generate(output: String) throws -> String {
    try fs.createDirectory(parentDirectory(output))
    try fs.write(Data(try render().utf8), to: output)
    return output
  }
}
