import Dependencies
import Foundation

public struct ShowcaseManifestGenerator {
  let registry: Registry
  @Dependency(\.registryFileSystem) var fs
  public static let outputPath =
    "Examples/Showcase/SwiftUIRegistryShowcasePackage/Sources/SwiftUIRegistryShowcaseFeature/RegistryCatalogManifest.swift"
  public static let namesPath =
    "Examples/Showcase/SwiftUIRegistryShowcaseUITests/RegistryItemNames.swift"
  public init(root: String) throws { registry = try Registry(root: root) }
  private let header = #"""
    // Generated by Scripts/generate_showcase_manifest.py from Registry metadata.
    // Do not edit by hand; edit the item document and regenerate.

    /// One registry item as the Showcase browses it.
    struct CatalogEntry: Identifiable, Hashable, Sendable {
        let name: String
        let kind: String
        let version: String
        let description: String
        let usage: String
        let dependencies: [String]
        let tags: [String]

        var id: String { name }
    }

    enum RegistryCatalogManifest {
        static let entries: [CatalogEntry] = [
    """# + "\n"
  private let footer = #"""
        ]

        static func entry(named name: String) -> CatalogEntry? {
            entries.first { $0.name == name }
        }

        static func entries(ofKind kind: String) -> [CatalogEntry] {
            entries.filter { $0.kind == kind }
        }
    }
    """# + "\n"
  private let namesHeader = #"""
    // Generated by Scripts/generate_showcase_manifest.py from Registry metadata.
    // Do not edit by hand; edit the item document and regenerate.

    /// Every registry item name by kind, for the UI suite's demo walk.
    enum RegistryItemNames {
    """# + "\n"

  public func render() -> String {
    var result = header
    for name in registry.items.keys.sorted() {
      let item = registry.items[name]!
      result += "        CatalogEntry(\n"
      for key in ["name", "kind", "version", "description", "usage"] {
        result += "            \(key): \(Self.swiftString(item[key].text)),\n"
      }
      let dependencies = item["registryDependencies"].strings.map(Self.swiftString).joined(
        separator: ", ")
      let tags = item["tags"].strings.map(Self.swiftString).joined(separator: ", ")
      result +=
        "            dependencies: [\(dependencies)],\n            tags: [\(tags)]\n        ),\n"
    }
    return result + footer
  }
  public func renderNames() -> String {
    var result = namesHeader
    for kind in ["component", "block", "recipe"] {
      let names = registry.items.keys.filter { registry.items[$0]!["kind"].text == kind }.sorted()
      result +=
        "    static let \(kind)s: [String] = [\(names.map(Self.swiftString).joined(separator: ", "))]\n"
    }
    return result + "\n    static var all: [String] { components + blocks + recipes }\n}\n"
  }
  public func generate(output: String, namesOutput: String) throws -> [String] {
    try fs.createDirectory(parentDirectory(output))
    try fs.write(Data(render().utf8), to: output)
    try fs.write(Data(renderNames().utf8), to: namesOutput)
    return [output, namesOutput]
  }
  static func swiftString(_ value: String) -> String {
    "\""
      + value.replacingOccurrences(of: "\\", with: "\\\\")
      .replacingOccurrences(of: "\"", with: "\\\"")
      .replacingOccurrences(of: "\n", with: "\\n")
      .replacingOccurrences(of: "\t", with: "\\t") + "\""
  }
}
