import Dependencies
import Foundation

/// Emits a Showcase source file that compiles every installable item's `usage`
/// snippet, one snippet per view, so a snippet that names an undeclared symbol
/// fails the Showcase build instead of shipping.
public struct UsageChecksGenerator {
  let registry: Registry
  @Dependency(\.registryFileSystem) var fs
  public static let outputPath =
    "Examples/Showcase/SwiftUIRegistryShowcasePackage/Sources/SwiftUIRegistryShowcaseFeature/UsageSnippetChecks.swift"

  public init(root: String) throws { registry = try Registry(root: root) }

  private static let header = #"""
    // Generated by `swiftui-registry generate usage-checks` from Registry metadata.
    // Do not edit by hand; edit the item document and regenerate.
    //
    // Each struct compiles one installable item's `usage` snippet, so a snippet
    // that names an undeclared symbol fails the Showcase build instead of
    // shipping. A symbol a snippet treats as the consumer's own code is a
    // stand-in declared in `UsageSnippetPlaceholders.swift`.

    """#

  public func render() -> String {
    let names =
      registry.items.keys
      .filter { registry.items[$0]!["kind"].text != "recipe" }
      .sorted()
    let usages = names.map { registry.items[$0]!["usage"].text }
    var result = Self.header
    if usages.contains(where: { $0.contains("BarMark") }) { result += "import Charts\n" }
    result += "import SwiftUI\nimport SwiftUIRegistryFoundations\n"
    for (name, usage) in zip(names, usages) {
      result += "\n" + Self.snippetStruct(name: name, usage: usage)
    }
    return result
  }

  public func generate(output: String) throws -> [String] {
    try fs.createDirectory(parentDirectory(output))
    try fs.write(Data(render().utf8), to: output)
    return [output]
  }

  // MARK: - Rendering one snippet

  enum Kind { case declaration, view, other }

  static func typeName(_ name: String) -> String {
    "UsageSnippet_"
      + name.split(separator: "-").map { $0.prefix(1).uppercased() + $0.dropFirst() }.joined()
  }

  /// The `UsageSnippet_<Name>` struct for one item: declaration statements as
  /// stored members, view statements in `body`, and any remaining statement in
  /// a `statements()` method emitted only when one exists.
  static func snippetStruct(name: String, usage: String) -> String {
    let statements = split(usage)
    var result = "// MARK: \(name)\n"
    result += "private struct \(typeName(name)): View {\n"
    for statement in statements where statement.kind == .declaration {
      for line in statement.lines { result += indent(line, 4) }
    }
    result += "    var body: some View {\n"
    for statement in statements where statement.kind == .view {
      for line in statement.lines { result += indent(line, 8) }
    }
    result += "    }\n"
    let others = statements.filter { $0.kind == .other }
    if !others.isEmpty {
      result += "    private func statements() {\n"
      for statement in others {
        for line in statement.lines { result += indent(line, 8) }
      }
      result += "    }\n"
    }
    return result + "}\n"
  }

  private static func indent(_ line: String, _ spaces: Int) -> String {
    String(repeating: " ", count: spaces) + line + "\n"
  }

  // MARK: - Splitting a snippet into statements

  struct Statement {
    var lines: [String]
    var kind: Kind
  }

  /// A new top-level statement begins at a non-blank line with no leading
  /// whitespace that does not continue the previous one (`.`, `}`, `)`).
  private static func startsStatement(_ line: String) -> Bool {
    let trimmed = line.trimmingCharacters(in: .whitespaces)
    guard !trimmed.isEmpty, let first = line.first, first != " ", first != "\t" else {
      return false
    }
    return !trimmed.hasPrefix(".") && !trimmed.hasPrefix("}") && !trimmed.hasPrefix(")")
  }

  private static func isBlank(_ line: String) -> Bool {
    line.trimmingCharacters(in: .whitespaces).isEmpty
  }

  private static func isComment(_ line: String) -> Bool {
    line.trimmingCharacters(in: .whitespaces).hasPrefix("//")
  }

  private static func trimBlanks(_ lines: [String]) -> [String] {
    var lines = lines
    while let first = lines.first, isBlank(first) { lines.removeFirst() }
    while let last = lines.last, isBlank(last) { lines.removeLast() }
    return lines
  }

  static func split(_ usage: String) -> [Statement] {
    var groups: [[String]] = []
    for line in usage.components(separatedBy: "\n") {
      if startsStatement(line) || groups.isEmpty {
        if isBlank(line) { continue }
        groups.append([line])
      } else {
        groups[groups.count - 1].append(line)
      }
    }
    // A comment-only group attaches to the statement that follows it, or, when
    // it trails everything, to the statement before it.
    var merged: [[String]] = []
    var pendingComment: [String] = []
    for group in groups.map(trimBlanks) {
      if group.allSatisfy({ isComment($0) || isBlank($0) }) {
        pendingComment += group
      } else {
        merged.append(pendingComment + group)
        pendingComment = []
      }
    }
    if !pendingComment.isEmpty {
      if merged.isEmpty {
        merged.append(pendingComment)
      } else {
        merged[merged.count - 1] += pendingComment
      }
    }
    return merged.map { Statement(lines: $0, kind: classify($0)) }
  }

  /// Classify a statement by its first non-comment line: a declaration keyword,
  /// a lowercase identifier being assigned or called, otherwise a view.
  static func classify(_ lines: [String]) -> Kind {
    guard let first = lines.first(where: { !isComment($0) && !isBlank($0) }) else { return .view }
    let trimmed = first.trimmingCharacters(in: .whitespaces)
    for keyword in ["@", "let ", "var ", "private ", "func ", "struct ", "enum "]
    where trimmed.hasPrefix(keyword) {
      return .declaration
    }
    if trimmed.range(
      of: #"^[a-z_][A-Za-z0-9_]*(\.[A-Za-z0-9_]+)*\s*(=|\+=|\()"#, options: .regularExpression)
      != nil
    {
      return .other
    }
    return .view
  }
}
