#!/usr/bin/env python3
"""Generate the static per-item catalog under docs/catalog from registry metadata.

The generator reads the registry through the validated Installer path (which
runs Scripts/registry_validation.py before anything else), so an invalid
catalog can never be documented. Output is deterministic and byte-stable:
no timestamps, sorted item order, and content derived only from metadata.
Tests/RegistryTests/test_catalog.py regenerates into a temporary directory
and asserts byte equality, so docs/catalog cannot drift from metadata.
"""

from __future__ import annotations

import argparse
import posixpath
import sys
from pathlib import Path

_SCRIPTS = Path(__file__).resolve().parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from install import Installer, RegistryError

_GENERATED_NOTE = (
    "<!-- Generated by Scripts/generate_catalog.py from Registry metadata."
    " Do not edit by hand; edit the item document and regenerate. -->"
)

# Deterministic group order for the index: value-led, blocks first. Each group
# carries the one line a scanner needs before clicking, above all whether the
# kind installs anything.
_KIND_GROUPS = [
    ("block", "Blocks", "Compositions of components. Installing one installs its whole closure"),
    ("component", "Components", "One installable style, modifier, or view each"),
    ("flow", "Flows", "Multi-screen compositions"),
    ("recipe", "Recipes", "Native guidance. Nothing installs; copy the snippet"),
]


def generate(repository_root: Path, output: Path) -> list[str]:
    """Write index.md plus one page per item; return the written file names."""
    installer = Installer(repository_root)
    output.mkdir(parents=True, exist_ok=True)

    written: list[str] = []
    for name in sorted(installer.items):
        page = f"{name}.md"
        (output / page).write_text(_item_page(installer, name), encoding="utf-8")
        written.append(page)

    (output / "index.md").write_text(_index_page(installer), encoding="utf-8")
    written.append("index.md")

    for stale in sorted(output.glob("*.md")):
        if stale.name not in written:
            stale.unlink()
    return written


def _index_page(installer: Installer) -> str:
    lines = [
        _GENERATED_NOTE,
        "",
        "# SwiftUIRegistry catalog",
        "",
        f"{len(installer.items)} items you copy into your app and own. Components"
        " and blocks install with one command:",
        "",
        "```sh",
        "python3 Scripts/install.py <name> --destination <your-target-dir>",
        "```",
        "",
    ]
    for kind, heading, summary in _KIND_GROUPS:
        names = sorted(n for n, item in installer.items.items() if item["kind"] == kind)
        if not names:
            continue
        lines.append(f"## {heading} ({len(names)})")
        lines.append("")
        lines.append(summary)
        lines.append("")
        for name in names:
            description = installer.items[name]["description"]
            lines.append(f"- [{name}]({name}.md): {description}")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def _item_page(installer: Installer, name: str) -> str:
    item = installer.items[name]
    is_recipe = item["kind"] == "recipe"
    lines = [
        _GENERATED_NOTE,
        "",
        f"# {name}",
        "",
        item["description"],
        "",
    ]

    preview = item.get("preview")
    lines.extend(_preview_lines(name, preview))

    if is_recipe:
        # A recipe has no command, so it gets a one-line note instead of an
        # Install heading that promises one.
        lines.append("Nothing to install. Copy the snippet below")
        lines.append("")
    else:
        lines.append("## Install")
        lines.append("")
        lines.append("```sh")
        lines.append(f"python3 Scripts/install.py {name} --destination <your-target-dir>")
        lines.append("```")
        lines.append("")
        lines.extend(_requirement_lines(installer.package_requirements(name)))

    lines.append("## Usage")
    lines.append("")
    lines.append("```swift")
    lines.extend(item["usage"].splitlines())
    lines.append("```")
    lines.append("")

    if is_recipe:
        lines.append("## Why native is enough")
        lines.append("")
        lines.extend(item["docs"].splitlines())
        lines.append("")

    lines.append("## Details")
    lines.append("")
    lines.append(f"- Kind: {item['kind']}")
    lines.append(f"- Version: {item['version']}")
    platforms = ", ".join(
        f"{platform['name']} {platform['minimumVersion']}+" for platform in item["platforms"]
    )
    lines.append(f"- Platforms: {platforms}")

    if not is_recipe:
        lines.append(_closure_line(installer, name))

    if item["accessibility"]:
        lines.append("- Accessibility contract:")
        for note in item["accessibility"]:
            lines.append(f"  - {note}")
    else:
        lines.append("- Accessibility contract: none declared")

    lines.extend(_source_lines(item, preview))

    return "\n".join(lines).rstrip("\n") + "\n"


def _requirement_lines(requirements: list[dict]) -> list[str]:
    """One sentence for the usual single requirement; a list only when there are several."""
    if not requirements:
        return ["Nothing else to add; this item has no package requirement", ""]
    if len(requirements) == 1:
        return [f"Then {Installer.dependency_instruction(requirements[0])}", ""]
    lines = ["Then add each package requirement to that target:", ""]
    lines.extend(f"- {Installer.dependency_instruction(entry)}" for entry in requirements)
    lines.append("")
    return lines


def _source_lines(item: dict, preview: dict | None) -> list[str]:
    """Name the copied files, marking the one that carries the Xcode preview."""
    if not item["files"]:
        return []
    preview_source = (preview or {}).get("source")
    preview_name = (preview or {}).get("name")

    def entry(source: str) -> str:
        rendered = f"[{source}]({_relative_link(f'Registry/{source}')})"
        if source == preview_source:
            rendered += f", with the `{preview_name}` Xcode preview"
        return rendered

    sources = [file["source"] for file in item["files"]]
    if len(sources) == 1:
        return [f"- Source: {entry(sources[0])}"]
    return ["- Source:"] + [f"  - {entry(source)}" for source in sources]


def _preview_lines(name: str, preview: dict | None) -> list[str]:
    """Lead with one screenshot; keep the alternates as a single link line."""
    screenshots = (preview or {}).get("screenshots") or []
    if not screenshots:
        return []
    lines = [f"![{name} preview]({_relative_link(screenshots[0])})", ""]
    alternates = [
        f"[{_screenshot_label(name, path)}]({_relative_link(path)})" for path in screenshots[1:]
    ]
    if alternates:
        lines.append(f"More previews: {', '.join(alternates)}")
        lines.append("")
    return lines


def _screenshot_label(name: str, screenshot: str) -> str:
    """Human label for an alternate screenshot, from the item-prefixed file stem."""
    stem = posixpath.basename(screenshot).rsplit(".", 1)[0]
    prefix = f"{name}-"
    if stem.startswith(prefix):
        stem = stem[len(prefix) :]
    return stem.replace("-", " ")


def _closure_line(installer: Installer, name: str) -> str:
    closure = installer.resolve(name)
    if closure == [name]:
        return "- Registry dependencies: none"
    rendered = ", ".join(
        f"[{member}]({member}.md) {installer.items[member]['version']}" for member in closure
    )
    return f"- Installs in order: {rendered}"


def _relative_link(repository_relative: str) -> str:
    """Relative markdown link from the catalog's canonical home to a repo-rooted path.

    Links are always computed as if the page lived in docs/catalog, so output
    bytes are identical wherever the caller writes them; the freshness test
    relies on that when it regenerates into a temporary directory.
    """
    return posixpath.relpath(repository_relative, "docs/catalog")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    repository_root = Path(__file__).resolve().parents[1]
    parser.add_argument(
        "--output",
        type=Path,
        default=repository_root / "docs" / "catalog",
        help="Directory to write the catalog into (default: docs/catalog)",
    )
    arguments = parser.parse_args()

    try:
        written = generate(repository_root, arguments.output)
    except RegistryError as error:
        parser.error(str(error))
    for page in written:
        print(f"wrote {arguments.output / page}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
