#!/usr/bin/env python3
"""Generate the Showcase catalog manifest from registry metadata.

The Showcase app browses every item by kind and renders each item's real
`usage` snippet next to its demo. Those strings come from `Registry/items/`
through this generator, never from hand-typed Swift, so the app can never show
a snippet that differs from the catalog. Output is deterministic and
`Tests/RegistryTests/test_showcase_manifest.py` rejects drift byte for byte.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

_SCRIPTS = Path(__file__).resolve().parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from install import Installer, RegistryError

DEFAULT_OUTPUT = Path(
    "Examples/Showcase/SwiftUIRegistryShowcasePackage/Sources/"
    "SwiftUIRegistryShowcaseFeature/RegistryCatalogManifest.swift"
)

# The UI test target cannot import the feature module's manifest, so it gets
# the item names (only) from the same generator, keeping the demo walk honest.
NAMES_OUTPUT = Path(
    "Examples/Showcase/SwiftUIRegistryShowcaseUITests/RegistryItemNames.swift"
)

_NAMES_HEADER = """// Generated by Scripts/generate_showcase_manifest.py from Registry metadata.
// Do not edit by hand; edit the item document and regenerate.

/// Every registry item name by kind, for the UI suite's demo walk.
enum RegistryItemNames {
"""

_HEADER = """// Generated by Scripts/generate_showcase_manifest.py from Registry metadata.
// Do not edit by hand; edit the item document and regenerate.

/// One registry item as the Showcase browses it.
struct CatalogEntry: Identifiable, Hashable, Sendable {
    let name: String
    let kind: String
    let version: String
    let description: String
    let usage: String
    let dependencies: [String]
    let tags: [String]

    var id: String { name }
}

enum RegistryCatalogManifest {
    static let entries: [CatalogEntry] = [
"""

_FOOTER = """    ]

    static func entry(named name: String) -> CatalogEntry? {
        entries.first { $0.name == name }
    }

    static func entries(ofKind kind: String) -> [CatalogEntry] {
        entries.filter { $0.kind == kind }
    }
}
"""


def _swift_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def render(repository_root: Path) -> str:
    installer = Installer(repository_root)
    lines = [_HEADER]
    for name in sorted(installer.items):
        item = installer.items[name]
        dependencies = ", ".join(_swift_string(d) for d in item["registryDependencies"])
        lines.append("        CatalogEntry(\n")
        lines.append(f"            name: {_swift_string(name)},\n")
        lines.append(f"            kind: {_swift_string(item['kind'])},\n")
        lines.append(f"            version: {_swift_string(item['version'])},\n")
        lines.append(f"            description: {_swift_string(item['description'])},\n")
        lines.append(f"            usage: {_swift_string(item['usage'])},\n")
        tags = ", ".join(_swift_string(t) for t in item["tags"])
        lines.append(f"            dependencies: [{dependencies}],\n")
        lines.append(f"            tags: [{tags}]\n")
        lines.append("        ),\n")
    lines.append(_FOOTER)
    return "".join(lines)


def render_names(repository_root: Path) -> str:
    installer = Installer(repository_root)
    lines = [_NAMES_HEADER]
    for kind in ("component", "block", "recipe"):
        names = sorted(n for n, item in installer.items.items() if item["kind"] == kind)
        rendered = ", ".join(_swift_string(n) for n in names)
        lines.append(f"    static let {kind}s: [String] = [{rendered}]\n")
    lines.append("\n    static var all: [String] { components + blocks + recipes }\n}\n")
    return "".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    repository_root = Path(__file__).resolve().parents[1]
    parser.add_argument("--output", type=Path, default=repository_root / DEFAULT_OUTPUT)
    arguments = parser.parse_args()
    try:
        content = render(repository_root)
    except RegistryError as error:
        parser.error(str(error))
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(content, encoding="utf-8")
    print(f"wrote {arguments.output}")
    names_output = repository_root / NAMES_OUTPUT
    names_output.write_text(render_names(repository_root), encoding="utf-8")
    print(f"wrote {names_output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
