#!/bin/zsh
# Rebuilds RoundTripFixture.swift, the round-trip instrument's compiled exports.
# The Showcase tests write every dataset state's Swift export and preset code;
# `swiftui-registry preset apply` writes each code's theme file; both are copied
# into the fixture verbatim, the theme lines of the Swift export and the
# initializer of the theme file, so the test target compiles exactly what a
# consuming app would. Each export is first typechecked as a consuming app
# builds it (the theme file whole, the Swift lines inside a function); one that
# fails is recorded with its first error instead of compiled.
# Usage: Scripts/round_trip_fixture.sh [simulator-udid]
set -euo pipefail

root=${0:A:h:h}
udid=${1:-1807166B-C557-4F6B-B177-D5F3F701CBD7}
fixture=$root/Examples/Showcase/SwiftUIRegistryShowcasePackage/Tests/SwiftUIRegistryShowcaseFeatureTests/RoundTripFixture.swift
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

# An empty fixture first, so a fixture that no longer compiles cannot block its own rebuild.
cat > $fixture <<'SEED'
// Generated by Scripts/round_trip_fixture.sh from the design surface's exports. Do not edit by hand.
import SwiftUI
import SwiftUIRegistryFoundations

enum RoundTripFixture {
    static let swiftSource: [String: String] = [:]
    static let presetCode: [String: String] = [:]
    static let swiftCompileError: [String: String] = [:]
    static let presetCompileError: [String: String] = [:]
    static func swiftTheme(_ id: String) -> RegistryTheme? { nil }
    static func presetTheme(_ id: String) -> RegistryTheme? { nil }
}
SEED

env TEST_RUNNER_ROUNDTRIP_EXPORT_DIR=$work xcodebuild test \
  -workspace $root/Examples/Showcase/SwiftUIRegistryShowcase.xcworkspace \
  -scheme SwiftUIRegistryShowcase \
  -destination "id=$udid" \
  -only-testing:SwiftUIRegistryShowcaseFeatureTests/RoundTripExport \
  -derivedDataPath $work/dd \
  -quiet > $work/export.log 2>&1 || { cat $work/export.log; exit 1; }

swift build --package-path $root --product swiftui-registry > /dev/null
cli=$(swift build --package-path $root --show-bin-path)/swiftui-registry

ids=(${(f)"$(cd $work && ls *.code | sed 's/\.code$//' | sort)"})
(( ${#ids} > 0 )) || { print -u2 "The export wrote no states."; exit 1; }
products=$work/dd/Build/Products/Debug-iphonesimulator
typecheck() {
  xcrun -sdk iphonesimulator swiftc -typecheck -target arm64-apple-ios26.0-simulator -I $products "$1" 2>&1 \
    | grep -m 1 'error:' | sed 's/.*error: //' || true
}
typeset -A swift_error preset_error
integer swift_failures=0 preset_failures=0
for id in $ids; do
  $cli preset apply "$(<$work/$id.code)" --destination $work/$id --force > /dev/null
  {
    print -r -- "import SwiftUI"
    print -r -- "import SwiftUIRegistryFoundations"
    print -r -- "import UIKit"
    print -r -- "@MainActor func make() -> RegistryTheme {"
    awk '/^$/ { exit } { print }' $work/$id.swift.txt
    print -r -- "return theme"
    print -r -- "}"
  } > $work/$id-swift.swift
  swift_error[$id]=$(typecheck $work/$id-swift.swift)
  preset_error[$id]=$(typecheck "$work/$id/RegistryTheme+App.swift")
  if [[ -n ${swift_error[$id]} ]]; then swift_failures+=1; fi
  if [[ -n ${preset_error[$id]} ]]; then preset_failures+=1; fi
done

# Prints one error dictionary, `[:]` when every export compiled.
errors() {
  local name=$1 table=$2 id
  if (( ${(P)${:-${table}_count}} == 0 )); then
    print -r -- "    static let $name: [String: String] = [:]"
    return
  fi
  print -r -- "    static let $name: [String: String] = ["
  for id in $ids; do
    if [[ -n ${${(P)table}[$id]} ]]; then print -r -- "        \"$id\": #\"${${(P)table}[$id]}\"#,"; fi
  done
  print -r -- "    ]"
}
swift_error_count=$swift_failures
preset_error_count=$preset_failures

{
  print -r -- "// Generated by Scripts/round_trip_fixture.sh from the design surface's exports. Do not edit by hand."
  print -r -- "import SwiftUI"
  print -r -- "import SwiftUIRegistryFoundations"
  print -r -- "import UIKit"
  print -r -- ""
  print -r -- "enum RoundTripFixture {"
  print -r -- "    static let swiftSource: [String: String] = ["
  for id in $ids; do
    print -r -- "        \"$id\": #\"\"\""
    sed 's/^/        /' $work/$id.swift.txt
    print -r -- ""
    print -r -- "        \"\"\"#,"
  done
  print -r -- "    ]"
  print -r -- ""
  print -r -- "    static let presetCode: [String: String] = ["
  for id in $ids; do
    print -r -- "        \"$id\": \"$(<$work/$id.code)\","
  done
  print -r -- "    ]"
  print -r -- ""
  print -r -- "    /// Exports that do not compile in a consuming app, with the compiler's first error."
  errors swiftCompileError swift_error
  print -r -- ""
  errors presetCompileError preset_error
  print -r -- ""
  print -r -- "    /// The Swift export's theme lines, as pasted; the export applies the result with \`.registryTheme(theme)\`."
  print -r -- "    static func swiftTheme(_ id: String) -> RegistryTheme? {"
  print -r -- "        switch id {"
  for id in $ids; do
    if [[ -n ${swift_error[$id]} ]]; then continue; fi
    print -r -- "        case \"$id\":"
    awk '/^$/ { exit } { print "            " $0 }' $work/$id.swift.txt
    print -r -- "            return theme"
  done
  print -r -- "        default:"
  print -r -- "            return nil"
  print -r -- "        }"
  print -r -- "    }"
  print -r -- ""
  print -r -- "    /// The initializer \`preset apply\` writes as \`RegistryTheme.app\`."
  print -r -- "    static func presetTheme(_ id: String) -> RegistryTheme? {"
  print -r -- "        switch id {"
  for id in $ids; do
    if [[ -n ${preset_error[$id]} ]]; then continue; fi
    print -r -- "        case \"$id\":"
    awk 'started && /^}$/ { exit }
         started { sub(/^    /, ""); print "            " $0 }
         /^    static let app = / { sub(/^    static let app = /, ""); print "            return " $0; started = 1 }' \
      "$work/$id/RegistryTheme+App.swift"
  done
  print -r -- "        default:"
  print -r -- "            return nil"
  print -r -- "        }"
  print -r -- "    }"
  print -r -- "}"
} > $fixture

print "Wrote ${#ids} states to ${fixture#$root/}; exports that do not compile: swift $swift_failures, preset $preset_failures"
